Transfer to Es modules
w3c/echidna pull request #1125
Opened 2023-04-03 05:21 UTC by jennyliang220

2023-04-18 12:28 UTC, deniak requested changes

2023-04-18 12:28 UTC, deniak commented on app.js
> +          await sendMessage(
is there any reason to use `await` here?

2023-04-18 12:28 UTC, deniak commented on config-dev.js
> +function setGlobalInfo() {
This is the dev config. In production, we are using a different config file based from `config.js.example`.

2023-04-18 13:40 UTC, deniak requested changes

2023-04-18 13:40 UTC, deniak commented on lib/history.js
> +// import(`../${config}`);
delete comments

2023-04-18 13:40 UTC, deniak commented on lib/orchestrator.js
> +// import(`../${config}`);
delete comments

2023-04-24 09:54 UTC, jennyliang220 commented
## [Import a module for its side effects only](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#import_a_module_for_its_side_effects_only)

```
(async () => {
  if (somethingIsTrue) {
    // import module for side effects
    await import("/modules/my-module.js");
  }
})();

```

This could work for the global variables.

2023-05-17 07:54 UTC, deniak approved these changes

2023-05-17 07:54 UTC, merged